### ISSUE TITLE
 does it work with nodemcu?

### ISSUE THREAD

**Issue by rogerin** [galbraithmedia1/ESP32-HomeSpan#1]
Hello, does it work with nodemcu?

**Comment by galbraithmedia1** [comment]
Yes it should work great!

**Comment by rogerin** [comment]
sorry, my question is if it works on esp8266

**Comment by galbraithmedia1** [comment]
Oh I see. It would probably work with some changes, but it would be best with an esp32.

**Comment by galbraithmedia1** [comment]
After looking more into it, HomeSpan Library is built for an esp32. Sorry

**Comment by galbraithmedia1** [comment]
After looking more into it, HomeSpan Library is built for an esp32. Sorry
